miproyecto/miproyecto/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from redes import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^redes/',include('redes.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

miproyecto/redes/urls.py
# redes/urls.py

from django.conf.urls import url
from redes import views
#from django.urls import path
#from .views import redirect_view

# SET THE NAMESPACE!
app_name = 'redes'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^perritos/$',views.perritos,name='perritos'),
]

miproyecto/redes/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here

class UserProfileInfo(models.Model):

	user = models.OneToOneField(User,on_delete=models.CASCADE)

	#portfolio_site = models.URLField(blank=True)

	#profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

	def __str__(self):
  		return self.user.username

miproyecto/redes/forms.py
from django import forms
from redes.models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())
	class Meta():
		model = User
		fields = ('username','email','password')


#class UserProfileInfoForm(forms.ModelForm):
#	class Meta():
#		model = UserProfileInfo    
#		fields = ('portfolio_site','profile_pic')

miproyecto/redes/views.py
from django.shortcuts import render
from redes.forms import UserForm #,UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect

def index(request):
    return render(request,'redes/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in !")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
    #return index(request)
    #return redirect("https://doggos.ml")
    #return redirect('www.doggos.ml')

def redirect_login(request):
    response = redirect("/redes/user_login/")
    return response

@login_required
def redirect_to_app(request):
    response = redirect("/redes/perritos/")
    return response

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        #profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid(): # and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            #profile = profile_form.save(commit=False)
            #profile.user = user
            #if 'profile_pic' in request.FILES:
            #    print('found it')
            #    profile.profile_pic = request.FILES['profile_pic']
            #profile.save()
            registered = True
            #return redirect_login(request)
            return HttpResponseRedirect(reverse('redes:user_login'))
        else:
            print(user_form.errors) #,profile_form.errors)
    else:
        user_form = UserForm()
        #profile_form = UserProfileInfoForm()
    return render(request,'redes/registration.html',
                          {'user_form':user_form,
                           #'profile_form':profile_form,
                           'registered':registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('redes:perritos'))
                #return redirect_to_app(request)
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'redes/login.html', {})

def perritos(request):
    current_user = request.user
    if current_user.is_authenticated:
        #return HttpResponseRedirect(reverse('redes:perritos'))
        #return redirect('redes:perritos')
        return render(request, 'redes/perritos.html', {})
        #return render(request, 'redes/index.html', {})
        #index(request)
    else:
        #return redirect('user_login')
        #return HttpResponseRedirect(reverse('user_login'))
        return render(request, 'redes/login.html', {})

miproyecto/redes/templates/redes/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"></head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'redes:register' %}">Register</a></li>     
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'redes:user_login' %}">Login</a></li>
          {% endif %}</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

miproyecto/redes/templates/redes/generic.html
{% load static %}

<!DOCTYPE HTML>
<!--
	Spectral by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Generic - Spectral by HTML5 UP</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static "css/mainIndex.css" %}"/>
		<noscript><link rel="stylesheet" href="{% static "css/noscript.css" %}"/></noscript>
	</head>
	<body class="is-preload">

		<!-- Page Wrapper -->
			<div id="page-wrapper">

				<!-- Header -->
					<header id="header">
						<h1><a href="index.html">Spectral</a></h1>
						<nav id="nav">
							<ul>
								<li class="special">
									<a href="#menu" class="menuToggle"><span>Menu</span></a>
									<div id="menu">
										<ul>
											<li><a href="index.html">Home</a></li>
											<li><a href="generic.html">Generic</a></li>
											<li><a href="elements.html">Elements</a></li>
											<li><a href="#">Sign Up</a></li>
											<li><a href="#">Log In</a></li>
										</ul>
									</div>
								</li>
							</ul>
						</nav>
					</header>

				<!-- Main -->
					<article id="main">
						<header>
							<h2>Generic Page</h2>
							<p>Aliquam ut ex ut interdum donec amet imperdiet eleifend</p>
						</header>
						<section class="wrapper style5">
							<div class="inner">

								<h3>Lorem ipsum dolor</h3>
								<p>Morbi mattis mi consectetur tortor elementum, varius pellentesque velit convallis. Aenean tincidunt lectus auctor mauris maximus, ac scelerisque ipsum tempor. Duis vulputate ex et ex tincidunt, quis lacinia velit aliquet. Duis non efficitur nisi, id malesuada justo. Maecenas sagittis felis ac sagittis semper. Curabitur purus leo, tempus sed finibus eget, fringilla quis risus. Maecenas et lorem quis sem varius sagittis et a est. Maecenas iaculis iaculis sem. Donec vel dolor at arcu tincidunt bibendum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce ut aliquet justo. Donec id neque ipsum. Integer eget ultricies odio. Nam vel ex a orci fringilla tincidunt. Aliquam eleifend ligula non velit accumsan cursus. Etiam ut gravida sapien.</p>

								<p>Vestibulum ultrices risus velit, sit amet blandit massa auctor sit amet. Sed eu lectus sem. Phasellus in odio at ipsum porttitor mollis id vel diam. Praesent sit amet posuere risus, eu faucibus lectus. Vivamus ex ligula, tempus pulvinar ipsum in, auctor porta quam. Proin nec dui cursus, posuere dui eget interdum. Fusce lectus magna, sagittis at facilisis vitae, pellentesque at etiam. Quisque posuere leo quis sem commodo, vel scelerisque nisi scelerisque. Suspendisse id quam vel tortor tincidunt suscipit. Nullam auctor orci eu dolor consectetur, interdum ullamcorper ante tincidunt. Mauris felis nec felis elementum varius.</p>

								<hr />

								<h4>Feugiat aliquam</h4>
								<p>Nam sapien ante, varius in pulvinar vitae, rhoncus id massa. Donec varius ex in mauris ornare, eget euismod urna egestas. Etiam lacinia tempor ipsum, sodales porttitor justo. Aliquam dolor quam, semper in tortor eu, volutpat efficitur quam. Fusce nec fermentum nisl. Aenean erat diam, tempus aliquet erat.</p>

								<p>Etiam iaculis nulla ipsum, et pharetra libero rhoncus ut. Phasellus rutrum cursus velit, eget condimentum nunc blandit vel. In at pulvinar lectus. Morbi diam ante, vulputate et imperdiet eget, fermentum non dolor. Ut eleifend sagittis tincidunt. Sed viverra commodo mi, ac rhoncus justo. Duis neque ligula, elementum ut enim vel, posuere finibus justo. Vivamus facilisis maximus nibh quis pulvinar. Quisque hendrerit in ipsum id tellus facilisis fermentum. Proin mauris dui, at vestibulum sit amet, auctor bibendum neque.</p>

							</div>
						</section>
					</article>

				<!-- Footer -->
					<footer id="footer">
						<ul class="icons">
							<li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
							<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
							<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
							<li><a href="#" class="icon brands fa-dribbble"><span class="label">Dribbble</span></a></li>
							<li><a href="#" class="icon solid fa-envelope"><span class="label">Email</span></a></li>
						</ul>
						<ul class="copyright">
							<li>&copy; Untitled</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
						</ul>
					</footer>

			</div>

		<!-- Scripts -->
			<script src="{% static "js/jquery.min.js" %}"></script>
			<script src="{% static "js/jquery.scrollex.min.js" %}"></script>
			<script src="{% static "js/jquery.scrolly.min.js" %}"></script>
			<script src="{% static "js/browser.min.js" %}"></script>
			<script src="{% static "js/breakpoints.min.js" %}"></script>
			<script src="{% static "js/util.js" %}"></script>
			<script src="{% static "js/mainIndex.js" %}"></script>

	</body>
</html>

miproyecto/redes/templates/redes/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Log in</title>
	<link rel="icon" href="{% static "/images/doggy.ico" %}">
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Para los iconos de los campos-->
	<link rel="stylesheet" type="text/css" href="{% static "/fonts/icon-font.min.css" %}">
	<!-- Todo el demas estilo de la pagina-->
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
	<link rel="stylesheet" type="text/css" href="{% static "/css/main.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "/css/util.css" %}">
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100" style="background-image: url({% static "/images/welcom-doggo.jpg" %});">
			<div class="wrap-login100 p-t-30 p-b-50">
				<span class="login100-form-title p-b-41">
					Welcome back
				</span>
				<form class="login100-form validate-form p-b-33 p-t-5" method="post" action="{% url 'redes:user_login' %}">
					{% csrf_token %}
					<div class="wrap-input100 validate-input" data-validate = "Enter username">
						<input class="input100" type="text" name="username" placeholder="Usuario">
						<span class="focus-input100" data-placeholder="&#xe82a;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<input class="input100" type="password" name="password" placeholder="Contraseña">
						<span class="focus-input100" data-placeholder="&#xe80f;"></span>
					</div>

					<div class="container-login100-form-btn m-t-32">
						<button class="login100-form-btn">
							Log in
						</button>
					</div>

				</form>
			</div>
		</div>
	</div>

</body>
</html>

miproyecto/redes/templates/redes/perritos.html
{% load static %}

<!DOCTYPE html>
<!--
TEMPLATE
Name: Zoo Planet
Version: 1.0
Created: 23 January 2014

AUTHOR
Design and code by: http://www.bootshape.com
Free stock photos by: http://www.bootshape.com

Read full license: http://www.bootshape.com/license.php

CREDITS
Background: http://subtlepatterns.com/ (extra_clean_paper)
Fonts: http://www.google.com/fonts (Actor, Duru_Sans)

SUPPORT
E-mail: bootshape.com@gmail.com
Contact: http://www.bootshape.com/contact.php
-->
<html>
  <head>
    <title>Adopt Doggos</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Title icon-->
    <link rel="icon" href="{% static "images/new-house.png" %}">
    <!-- Bootstrap -->
    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet">
    <!--Google Fonts-->
    <link href='http://fonts.googleapis.com/css?family=Duru+Sans|Actor' rel='stylesheet' type='text/css'>
    <!--Bootshape-->
    <link href="{% static "css/bootshape.css" %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- Navigation bar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Get a <span class="green">DOGGO</span></a>
        </div>
        <nav role="navigation" class="collapse navbar-collapse navbar-right">
          <ul class="navbar-nav nav">
            <li class="active" style="font-size: medium;"><a href="#">Home</a></li>
            <li class="dropdown">
              <a data-toggle="dropdown" href="#" class="dropdown-toggle">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="http://www.vetstreet.com/learn/adopting-instead-of-buying-a-pet">Adopt Instead of Buying</a></li>
                <li class="active"><a href="https://www.wikihow.pet/Take-Care-of-a-Dog">How to Take Care of a Dog</a></li>
                <li><a href="https://www.care.com/c/stories/6124/25-reasons-dogs-are-the-best-things-on-earth/">Why they are the best!?</a></li>
                <li class="divider"></li>
                <li><a href="https://www.buzzfeed.com/hattiesoykan/the-100-best-dog-memes-of-all-time">Funny doggos</a></li>
              </ul>
            </li>
            <li><a href="#" style="font-size: medium;">About us</a></li>
            <li><a href="#" style="font-size: medium;">Requirements</a></li>
            <!-- <li><a href="http://doggos.ml" style="font-size: medium;"  >Log out</a></li> -->
            <li><a href="{% url 'logout' %}">Logout</a></li>
          </ul>
        </nav>
      </div>
    </div><!-- End Navigation bar -->

    <!-- Slide gallery -->
    <div class="jumbotron">
      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-generic" data-slide-to="1"></li>
          <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>
        <!-- Wrapper for slides -->
        <div class="carousel-inner">
          <div class="item active">
            <img src="{% static "images/carousel1.jpg" %}" alt="" style="display: block; margin: 0 auto; width: 72%;">
            <div class="carousel-caption">
            </div>
          </div>
          <div class="item">
            <img src="{% static "images/carousel2.jpg" %}" alt="" style="display: block; margin: 0 auto; width: 70%;">
            <div class="carousel-caption">
            </div>
          </div>
          <div class="item">
            <img src="{% static "images/carousel3.jpg" %}" alt="" style="display: block; margin: 0 auto; width: 73%;">
            <div class="carousel-caption">
            </div>
          </div>
        </div>
        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      </div>
    </div><!-- End Slide gallery -->
    <h3 class="text-center" style="font-size: xx-large; text-decoration: underline overline #5cb85c;">
      <span class="green">Dogs of the month</span></h3>
    <!-- Thumbnails -->
    <div class="container thumbs">
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <img src="{% static "images/pic1.png" %}" alt="" class="img-circle">
          <div class="caption">
            <h3 class="text-center">Daimond</h3>
            <p style="font-size: large;"> Diamond is like a bottle of champagne; bubbly and sweet, and always something to look forward to. She is an exuberant little lady, and is more than ready for a home of her own. We think she is around 6 years old, and she looks like a Pit Bull mix. Diamond is bouncy and exuberant and would do fantastic in a home with kids and potentially another dog.</p>
            <div class="btn-toolbar text-center">
              <a href="https://adopt-a-dog.org/what-we-do/adoptions/dogs/diamond-og.html" 
                role="button" class="btn btn-success">Adopt</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <img src="{% static "images/pic2.jpg" %}" alt="" class="img-circle">
          <div class="caption">
            <h3 class="text-center">Maca</h3>
            <p style="font-size:large">Female. 1 year old. Big size.
              It has a lot of energy. Highly sociable with people. She is a bit  dominant with dogs but can socialize without problems. She requires constant physical activity and it is highly recommended that you don't let her spend too much time alone.</p>
            <div class="btn-toolbar text-center">
              <a href="https://cambiaundestino.org/perros-gatos-en-adopcion/maca/" 
                role="button" class="btn btn-success" style="margin-top: 51px;">Adopt</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <img src="{% static "images/pic3.jpeg" %}" alt="" class="img-circle">
          <div class="caption">
            <h3 class="text-center">Tessa</h3>
            <p style="font-size:large;">Tessa is a 5 year old Heeler mix. Loyal and attentive, as her heeler breed indicates. She prefers friends of the canine family. Tessa has waited awhile to meet her forever family. She is a wonderful companion and is ready for love. </p>
            <div class="btn-toolbar text-center">
              <a href="https://www.petfinder.com/dog/tessa-36259138/tx/mcallen/dr-dolittles-rescue-ranch-tx1177/" 
                role="button" class="btn btn-success" style="margin-top: 24px;">Adopt</a>
            </div>
          </div>
        </div>
      </div>
    </div><!-- End Thumbnails -->
    <!-- Content -->
    <div class="container">
      <h3 class="text-center">Welcome to Get a DOGGO</h3>
      <p style="font-size: large;">Our mission is to save, socialize and secure loving homes for unwanted or abandoned dogs. Get a DOGGO accomplishes this goal by providing the highest standard of care for dogs in need with a particular focus on ensuring that all aspects of their overall health and well-being are addressed.</br>
        Our vision is to create a community where there is a home for every dog.</p>
    </div><!-- End Content -->
    <!-- Footer -->
    <div class="footer text-center">
        <p style="font-size: xx-small;">&copy; 2014 Zoo Planet. All Rights Reserved. Proudly created by <a class="green" href="http://bootshape.com">Bootshape.com</a></p>
    </div><!-- End Footer -->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <!-- // <script src="https://code.jquery.com/jquery.js"></script> -->
    <script src="{% static "js/jquery.js" %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/bootshape.js" %}"></script>
    
  </body>
</html>

miproyecto/redes/templates/redes/registration.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Sign up</title>
	<!-- Para el icono del titulo-->
	<link rel="icon" href="{% static "/images/doggy.ico" %}">
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Para los iconos de los campos-->
	<link rel="stylesheet" type="text/css" href="{% static "/fonts/icon-font.min.css" %}">
	<!-- Todo el demas estilo de la pagina-->
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
	<link rel="stylesheet" type="text/css" href="{% static "/css/main.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "/css/util.css" %}">
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100" style="background-image: url({% static "/images/welcom-doggo.jpg" %});">
			<div class="wrap-login100 p-t-30 p-b-50">
				<span class="login100-form-title p-b-41">
					Be part of the family
				</span>
				<form class="login100-form validate-form p-b-33 p-t-5" method="post">
                    {% csrf_token %}
					<div class="wrap-input100 validate-input" data-validate = "Enter username">
						<input class="input100" type="text" name="username" placeholder="Usuario">
						<span class="focus-input100" data-placeholder="&#xe82a;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<input class="input100" type="text" name="email" placeholder="Correo">
						<span class="focus-input100" data-placeholder="&#xe818;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<input class="input100" type="password" name="password" placeholder="Contraseña">
						<span class="focus-input100" data-placeholder="&#xe80f;"></span>
					</div>

					<div class="container-login100-form-btn m-t-32">
						<button class="login100-form-btn">
							Sign up
						</button>
					</div>

				</form>
			</div>
		</div>
	</div>

</body>
</html>